---
functional:
  - Игрок должен иметь возможность регистрации и аутентификации на сайте при помощи email и пароля
  - Игрок должен иметь возможность восстановить пароль при помощи кнопки «forgot your password?»
  - Игрок должен иметь возможность регистрации и аутентификации на сайте при помощи Github
  - Игрок должен иметь возможность регистрации и аутентификации на сайте при помощи Discrod
  - Игрок должен иметь возможность сыграть матч без регистрации на сайте
  - Игрок должен иметь возможность создать игру с ботом 
  - Игрок должен иметь возможность создать игру с другим игроком
  - Игрок должен иметь возможность создать в турниры
  - Игрок должен иметь возможность участвовать в турнирах, созданных другими игроками
  - Игрок должен иметь возможность поделиться ссылкой для совместной игры с друзьями
  - Игрок должен иметь возможность видеть написание кода у соперника
  - На сайте должен быть реализован профиль пользователя
  - Игрок должен иметь возможность изменить используемый язык программирования в своем профиле
  - На сайте должна быть реализована система расчета и отображения рейтинга пользователей
  - На сайте должна быть реализована возможность общаться с другими игроками в чате
  - Игрок должен иметь возможность смотреть за чужими матчами
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика (минимум 1000 одновременных пользователей)
implicit:
  - Сайт должен запоминать авторизованного пользователя
  - Обработка персональных данных пользователя должна соответствовать требованиям безопасности
  - Имя пользователя должно быть уникальным
  - Адрес электронной почты должен быть уникальным
