---
functional:
  - Пользователь должен иметь возможность зарегистрироваться и войти в аккаунт
  - Пользователь должен иметь возможность восстановить пароль при помощи кнопки «forgot your password?»
  - Пользователь должен иметь возможность зарегистрироваться и войти на сайт при помощи Github
  - Пользователь должен иметь возможность зарегистрироваться и войти на сайт при помощи Discord
  - Пользователь должен иметь возможность сыграть матч без регистрации на сайте
  - Пользователь должен иметь возможность создать игру с ботом
  - Пользователь должен иметь возможность создать игру с другим игроком
  - Пользователь должен иметь возможность создать в турниры
  - Пользователь должен иметь возможность участвовать в турнирах, созданных другими игроками
  - Пользователь должен иметь возможность поделиться ссылкой для совместной игры с друзьями
  - Пользователь должен иметь возможность видеть написание кода у соперника
  - На сайте должен быть реализован профиль пользователя
  - Пользователь должен иметь возможность изменить используемый язык программирования в своем профиле
  - Пользователь должен иметь возможность изменить язык программирования во время матча
  - На сайте должна быть реализована система расчета и отображения рейтинга пользователей
  - На сайте должно отображаться количество игроков онлайн
  - На сайте должна быть реализована возможность общаться с другими игроками в чате
  - Пользователь должен иметь возможность смотреть за матчем других игроков
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика (минимум 1000 одновременных пользователей)
implicit:
  - Сайт должен запоминать авторизованного пользователя
  - При регистрации игрок должен начинать с нулем побед и с нулевым рейтингом
  - Обработка персональных данных пользователя должна соответствовать требованиям безопасности
  - Имя пользователя должно быть уникальным
  - Адрес электронной почты должен быть уникальным
  - Проверка решений осуществляется автоматически по тестам
  - Пользователь должен иметь возможность прекратить игру досрочно или перезагрузить её
