---
functional:
  - Игрок должен иметь возможность зарегистрироваться при помощи email и пароля
  - Игрок должен иметь возможность авторизоваться при помощи email и пароля
  - Игрок должен иметь возможность зарегистрироваться с помощью сторонних сервисов
  - Игрок должен иметь возможность авторизоваться с помощью сторонних сервисов
  - Сайт должен представить двум игрокам возможность соревноваться друг с другом в решении задач
  - Игрок должен иметь возможность видеть написание кода у соперника
  - Игрок должен иметь возможность видеть свой рейтинг
  - Игрок должен иметь возможность создать свою игру с ботом
  - Игрок должен иметь возможность поделиться ссылкой для совместной игры с друзьями
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика (минимум 1000 одновременных пользователей)
implicit:
  - Сайт должен запоминать авторизованного пользователя
